### ISSUE TITLE
doc about kv is missing

### ISSUE THREAD

**Issue by tessus** [atuinsh/docs#49]
Documentation for `atuin kv` is not available.

I only saw the `kv` subcommand by invoking `atuin --help`.

**Comment by ellie** [comment]
It's intentional for the time being 

I'm unsure about its longevity, or the interface remaining the same

**Comment by tessus** [comment]
ah, I see. in that case I'll close the issue. thanks.

**Comment by tessus** [comment]
btw, I think the idea is a good one and this functionality can be useful. however, the usage is a bit weird IMO:

`atuin kv set [OPTIONS] --key <KEY> <VALUE>` there's no need for `--key`

The following would be more than enough: `atuin kv set [OPTIONS] <KEY> <VALUE>` (the last 2 are the kv)
